#!/usr/bin/env python3
"""Generate the ProVerif models of the EST profile of TACRA from one template, so that the
variants differ only in the lines the pull request changes.

Enrollment. The Attester asks the conduit to initiate for its Target (TACRA Section 5.1), checks
server_id against the EST Server it is configured to use for that Target, and binds the Handle
(and, per variant, server_id and Target) and its CSR into Evidence. A server accepts any Target
the conduit names at initiation, requires the same Target in the second leg, verifies Evidence,
proof of possession and the binding, and issues. Queries:
  Q1  Issued(sid, t, x) ==> AttesterIntends(sid, t', x)     the right server, any Target
  Q2  Issued(sid, t, x) ==> AttesterIntends(sid, t, x)      the right server and the right Target
  Q3  inj-event version of Q2                               no second issuance per intent
Retrieval. The same first leg; the Vault releases its secret encrypted to CEKpub, in base mode or
with sender authentication (HPKE mode_auth). Query:
  R1  AttesterUses(vid, t, s) ==> VaultReleased(vid, t, s)

The attacker is the network: the untrusted conduit of TACRA Section 7.2. Variants add a
compromised second server, or a leaked TEE attestation key, to state what the result depends on.
"""
import os

HEADER = """(* {title}
   Generated by gen.py; do not edit by hand. ProVerif 2.05 syntax. *)

free c: channel.

type skey.
type pkey.
fun pk(skey): pkey.
fun pk2b(pkey): bitstring [data].

fun sign(bitstring, skey): bitstring.
reduc forall m: bitstring, k: skey; checksig(sign(m, k), pk(k)) = m.

fun h(bitstring): bitstring.

fun aenc(bitstring, pkey): bitstring.
reduc forall m: bitstring, k: skey; adec(aenc(m, pk(k)), k) = m.
fun aenc_auth(bitstring, pkey, skey): bitstring.
reduc forall m: bitstring, kr: skey, ks: skey; adec_auth(aenc_auth(m, pk(kr), ks), kr, pk(ks)) = m.

free tk: skey [private].
const meas: bitstring.
const id1: bitstring.
const id2: bitstring.
const tA: bitstring.
const tB: bitstring.
free ca1: skey [private].
free ca2: skey [private].
free vk1: skey [private].
free vk2: skey [private].
free sec1: bitstring [private].
free sec2: bitstring [private].

event AttesterIntends(bitstring, bitstring, bitstring).
event Issued(bitstring, bitstring, bitstring).
event VaultReleased(bitstring, bitstring, bitstring).
event AttesterUses(bitstring, bitstring, bitstring).
"""

def enrollment(variant: str) -> str:
    # variant: nobind (-00) | serveronly | bind | bind-compromised-s2 | bind-tee-key-leaked
    if variant == "nobind":
        a_in = "in(c, n: bitstring);"
        a_rd = "h((n, csr))"
        s_out = "out(c, n);"
        s_rd = "h((n, csr))"
        title = "Enrollment as in draft -00: Evidence binds the Handle and the CSR"
    elif variant == "serveronly":
        a_in = "in(c, (n: bitstring, sid: bitstring));\n  if sid = srv then"
        a_rd = "h((n, srv, csr))"
        s_out = "out(c, (n, id));"
        s_rd = "h((n, id, csr))"
        title = "Enrollment with server_id bound but not the Target"
    else:
        a_in = "in(c, (n: bitstring, sid: bitstring));\n  if sid = srv then"
        a_rd = "h((n, srv, tgt, csr))"
        s_out = "out(c, (n, id));"
        s_rd = "h((n, id, tgt, csr))"
        title = {"bind": "Enrollment with the pull request's binding: Handle, server_id, Target and CSR",
                 "bind-compromised-s2": "Enrollment with the full binding; the second server and its CA key are the attacker's",
                 "bind-tee-key-leaked": "Enrollment with the full binding; the TEE attestation key has leaked (an assumption made explicit)"}[variant]
    if variant == "bind-compromised-s2":
        queries = """
query t: bitstring, x: bitstring; event(Issued(id1, t, x)) ==> event(AttesterIntends(id1, t, x)).
"""
        proc = "out(c, pk(tk)); out(c, pk(ca1)); out(c, ca2);\n  ( !Attester(id1, tA) | !Server(id1, ca1) )"
    else:
        queries = """
query sid: bitstring, t: bitstring, t2: bitstring, x: bitstring; event(Issued(sid, t, x)) ==> event(AttesterIntends(sid, t2, x)).
query sid: bitstring, t: bitstring, x: bitstring; event(Issued(sid, t, x)) ==> event(AttesterIntends(sid, t, x)).
query sid: bitstring, t: bitstring, x: bitstring; inj-event(Issued(sid, t, x)) ==> inj-event(AttesterIntends(sid, t, x)).
"""
        leak = " out(c, tk);" if variant == "bind-tee-key-leaked" else ""
        proc = "out(c, pk(tk)); out(c, pk(ca1)); out(c, pk(ca2));" + leak + "\n  ( !Attester(id1, tA) | !Server(id1, ca1) | !Server(id2, ca2) )"
    return HEADER.format(title=title) + queries + f"""
let Attester(srv: bitstring, tgt: bitstring) =
  new csk: skey;
  let csr = (pk2b(pk(csk)), sign(pk2b(pk(csk)), csk)) in
  out(c, tgt);
  {a_in}
  event AttesterIntends(srv, tgt, csr);
  let ev = sign((meas, {a_rd}), tk) in
  out(c, (tgt, csr, ev)).

let Server(id: bitstring, ca: skey) =
  in(c, tgt: bitstring);
  new n: bitstring;
  {s_out}
  in(c, (tgt2: bitstring, csr: bitstring, ev: bitstring));
  if tgt2 = tgt then
  let (m: bitstring, rd: bitstring) = checksig(ev, pk(tk)) in
  if m = meas then
  let (pkcb: bitstring, pop: bitstring) = csr in
  let pk2b(pkc) = pkcb in
  if checksig(pop, pkc) = pkcb then
  if rd = {s_rd} then
  event Issued(id, tgt, csr);
  out(c, sign((id, tgt, pkcb), ca)).

process
  {proc}
"""

def retrieval(variant: str) -> str:
    # variant: base (-00) | auth | auth-compromised-vault2
    auth = variant.startswith("auth")
    dec = "adec_auth(b, cek, vpk)" if auth else "adec(b, cek)"
    enc = "aenc_auth(sec, pkc, vk)" if auth else "aenc(sec, pkc)"
    title = {"base": "Retrieval as in draft -00: bundle encrypted to CEKpub (base mode)",
             "auth": "Retrieval with origin authentication of the bundle (HPKE mode_auth)",
             "auth-compromised-vault2": "Retrieval with origin authentication; the second Vault's keys are the attacker's"}[variant]
    if variant == "auth-compromised-vault2":
        proc = "out(c, pk(tk)); out(c, pk(vk1)); out(c, vk2); out(c, sec2);\n  ( !AttesterR(id1, tA, pk(vk1)) | !Vault(id1, vk1, sec1) )"
    else:
        proc = "out(c, pk(tk)); out(c, pk(vk1)); out(c, pk(vk2));\n  ( !AttesterR(id1, tA, pk(vk1)) | !Vault(id1, vk1, sec1) | !Vault(id2, vk2, sec2) )"
    return HEADER.format(title=title) + """
query vid: bitstring, t: bitstring, s: bitstring; event(AttesterUses(vid, t, s)) ==> event(VaultReleased(vid, t, s)).
query attacker(sec1).
""" + f"""
let AttesterR(srv: bitstring, tgt: bitstring, vpk: pkey) =
  new cek: skey;
  out(c, tgt);
  in(c, (n: bitstring, sid: bitstring));
  if sid = srv then
  let ev = sign((meas, h((n, srv, tgt, pk2b(pk(cek))))), tk) in
  out(c, (tgt, pk2b(pk(cek)), ev));
  in(c, b: bitstring);
  let s = {dec} in
  event AttesterUses(srv, tgt, s).

let Vault(id: bitstring, vk: skey, sec: bitstring) =
  in(c, tgt: bitstring);
  new n: bitstring;
  out(c, (n, id));
  in(c, (tgt2: bitstring, pkcb: bitstring, ev: bitstring));
  if tgt2 = tgt then
  let pk2b(pkc) = pkcb in
  let (m: bitstring, rd: bitstring) = checksig(ev, pk(tk)) in
  if m = meas then
  if rd = h((n, id, tgt, pkcb)) then
  event VaultReleased(id, tgt, sec);
  out(c, {enc}).

process
  {proc}
"""

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    for f in os.listdir(here):
        if f.endswith(".pv"):
            os.remove(os.path.join(here, f))
    files = {
        "enrollment-nobind.pv": enrollment("nobind"),
        "enrollment-serveronly.pv": enrollment("serveronly"),
        "enrollment-bind.pv": enrollment("bind"),
        "enrollment-bind-compromised-s2.pv": enrollment("bind-compromised-s2"),
        "enrollment-bind-tee-key-leaked.pv": enrollment("bind-tee-key-leaked"),
        "retrieval-base.pv": retrieval("base"),
        "retrieval-auth.pv": retrieval("auth"),
        "retrieval-auth-compromised-vault2.pv": retrieval("auth-compromised-vault2"),
    }
    for name, text in files.items():
        with open(os.path.join(here, name), "w") as f:
            f.write(text)
        print("wrote", name)
