#!/usr/bin/env python3
"""Generate the ProVerif models of the EST profile of TACRA from one template, so that the
variants differ only in the lines the pull request changes.

Enrollment. The Attester asks the conduit to initiate for its Target (TACRA Section 5.1), checks
server_id against the EST Server it is configured to use for that Target, and binds the Handle
(and, per variant, server_id and Target) and its CSR into Evidence. A server accepts any Target
the conduit names at initiation, requires the same Target in the second leg, verifies Evidence,
proof of possession and the binding, and issues. Queries:
  Q1  Issued(sid, t, x) ==> AttesterIntends(sid, t', x)     the right server, any Target
  Q2  Issued(sid, t, x) ==> AttesterIntends(sid, t, x)      the right server and the right Target
  Q3  inj-event version of Q2                               no second issuance per intent
  B1  Issued(sid, t, x) ==> AttesterBinds(sid, t, x)        the server whose identity the Attester bound
  B2  inj-event version of B1
  U1  Issued(s1, t, x) && Issued(s2, t, x) ==> s1 = s2      at most one server issues for a CSR and Target
The rrp-source variants ask where the server identity in the binding comes from (rrp: the RATS
Relying Party, here the issuing server): the Attester binds either the server_id it receives in the
initiation response, from the conduit, or the one in its own configuration; and the first leg
returns either a fresh Handle per server session or a shared public epoch ep (absent-epoch with a
remote initiate), which the server recomputes the binding with.
The freshness-source variants cross the same three sources of the bound identity (none, received,
configured) with three more sources of freshness: the epoch value the Attester receives in the
initiation response (present-epoch style) in place of ep; Handles issued by a Verifier and accepted
by both servers (one Handle originator shared across Relying Parties); and a timestamp of the
Attester's own, sent in the request (absent-timestamp), abstracted as a fresh public value.
Retrieval. The same first leg; the Vault releases its secret encrypted to CEKpub, in base mode or
with sender authentication (HPKE mode_auth). Query:
  R1  AttesterUses(vid, t, s) ==> VaultReleased(vid, t, s)

The attacker is the network: the untrusted conduit of TACRA Section 7.2. Variants add a
compromised second server, or a leaked TEE attestation key, to state what the result depends on.
"""
import os

HEADER = """(* {title}
   Generated by gen.py; do not edit by hand. ProVerif 2.05 syntax. *)

free c: channel.

type skey.
type pkey.
fun pk(skey): pkey.
fun pk2b(pkey): bitstring [data].

fun sign(bitstring, skey): bitstring.
reduc forall m: bitstring, k: skey; checksig(sign(m, k), pk(k)) = m.

fun h(bitstring): bitstring.

fun aenc(bitstring, pkey): bitstring.
reduc forall m: bitstring, k: skey; adec(aenc(m, pk(k)), k) = m.
fun aenc_auth(bitstring, pkey, skey): bitstring.
reduc forall m: bitstring, kr: skey, ks: skey; adec_auth(aenc_auth(m, pk(kr), ks), kr, pk(ks)) = m.

free tk: skey [private].
const meas: bitstring.
const id1: bitstring.
const id2: bitstring.
const tA: bitstring.
const tB: bitstring.
free ca1: skey [private].
free ca2: skey [private].
free vk1: skey [private].
free vk2: skey [private].
free sec1: bitstring [private].
free sec2: bitstring [private].

event AttesterIntends(bitstring, bitstring, bitstring).
event Issued(bitstring, bitstring, bitstring).
event VaultReleased(bitstring, bitstring, bitstring).
event AttesterUses(bitstring, bitstring, bitstring).
"""

Q1 = "query sid: bitstring, t: bitstring, t2: bitstring, x: bitstring; event(Issued(sid, t, x)) ==> event(AttesterIntends(sid, t2, x)).\n"
Q2 = "query sid: bitstring, t: bitstring, x: bitstring; event(Issued(sid, t, x)) ==> event(AttesterIntends(sid, t, x)).\n"
Q3 = "query sid: bitstring, t: bitstring, x: bitstring; inj-event(Issued(sid, t, x)) ==> inj-event(AttesterIntends(sid, t, x)).\n"
B1 = "query sid: bitstring, t: bitstring, x: bitstring; event(Issued(sid, t, x)) ==> event(AttesterBinds(sid, t, x)).\n"
B2 = "query sid: bitstring, t: bitstring, x: bitstring; inj-event(Issued(sid, t, x)) ==> inj-event(AttesterBinds(sid, t, x)).\n"
U1 = "query s1: bitstring, s2: bitstring, t: bitstring, x: bitstring; event(Issued(s1, t, x)) && event(Issued(s2, t, x)) ==> s1 = s2.\n"
RRP_SOURCE = ("rrp-from-initiate", "nonce-norrp-uniqueness", "nonce-rrp-configured-uniqueness",
              "epoch-norrp", "epoch-rrp-from-initiate", "epoch-rrp-configured")
FRESHNESS = ("epoch-received", "verifier-handles", "timestamp")
FRESHNESS_SOURCES = tuple(f"{g}-{r}" for g in FRESHNESS for r in ("norrp", "rrp-from-initiate", "rrp-configured"))

def enrollment(variant: str) -> str:
    # variant: nobind (-00) | serveronly | bind | bind-nocompare | bind-compromised-s2 | bind-tee-key-leaked
    #   rrp source: rrp-from-initiate | nonce-norrp-uniqueness | nonce-rrp-configured-uniqueness
    #               | epoch-norrp | epoch-rrp-from-initiate | epoch-rrp-configured
    #   freshness source: {epoch-received | verifier-handles | timestamp}-{norrp | rrp-from-initiate | rrp-configured}
    decls = ""                        # declarations only some rrp-source variants need
    a_binds = ""                      # event AttesterBinds, where the Attester binds a server_id it received
    s_new = "new n: bitstring;\n  "   # the Handle; the epoch and timestamp variants have none
    a_ts = s_ts = ""                  # the timestamp field of the request, in the timestamp variants
    v_def = v_par = ""                # the Verifier that issues Handles, in the verifier-handles variants
    if variant in ("nobind", "nonce-norrp-uniqueness"):
        a_in = "in(c, n: bitstring);"
        a_rd = "h((n, csr))"
        s_out = "out(c, n);"
        s_rd = "h((n, csr))"
        title = {"nobind": "Enrollment as in draft -00: Evidence binds the Handle and the CSR",
                 "nonce-norrp-uniqueness": "Enrollment as in draft -00 (Handle and CSR bound, no server identity), asking only whether two servers can issue for one CSR and Target"}[variant]
    elif variant == "serveronly":
        a_in = "in(c, (n: bitstring, sid: bitstring));\n  if sid = srv then"
        a_rd = "h((n, srv, csr))"
        s_out = "out(c, (n, id));"
        s_rd = "h((n, id, csr))"
        title = "Enrollment with server_id bound but not the Target"
    elif variant == "rrp-from-initiate":
        # No server identity in the Attester's configuration: it binds the server_id it receives in
        # the initiation response, as the conduit delivers it, and compares it with nothing.
        decls = "event AttesterBinds(bitstring, bitstring, bitstring).\n"
        a_in = "in(c, (n: bitstring, sid: bitstring));"
        a_binds = "\n  event AttesterBinds(sid, tgt, csr);"
        a_rd = "h((n, sid, tgt, csr))"
        s_out = "out(c, (n, id));"
        s_rd = "h((n, id, tgt, csr))"
        title = "Enrollment with a fresh Handle per initiation; the Attester has no configured server identity and binds the server_id it receives in the initiation response, without comparison"
    elif variant in FRESHNESS_SOURCES:
        # Three more sources of freshness, each with the three sources of the server identity the
        # Attester binds: none (norrp), the server_id received in the initiation response
        # (rrp-from-initiate), or its own configuration (rrp-configured); no comparison in any.
        group = next(g for g in FRESHNESS if variant.startswith(g + "-"))
        rrp = variant[len(group) + 1:]
        a_sid = {"norrp": "", "rrp-from-initiate": "sid, ", "rrp-configured": "srv, "}[rrp]
        s_sid = "" if rrp == "norrp" else "id, "
        if group == "epoch-received":
            # Present-epoch style: as the epoch- variants (no Handle; the server returns the public
            # epoch ep and recomputes with ep), but the Attester binds the epoch value it receives.
            decls = "const ep: bitstring.\n"
            s_new = ""
            a_in = "in(c, e: bitstring);" if rrp == "norrp" else "in(c, (e: bitstring, sid: bitstring));"
            s_out = "out(c, ep);" if rrp == "norrp" else "out(c, (ep, id));"
            a_rd = f"h((e, {a_sid}tgt, csr))"
            s_rd = f"h((ep, {s_sid}tgt, csr))"
            fresh = "the epoch value"
            title = "Enrollment with a shared public epoch in place of a fresh Handle, the Attester binding the epoch value it receives in the initiation response (present-epoch style)"
        elif group == "verifier-handles":
            # A Verifier issues Handles and both servers accept them (one Handle originator shared
            # across Relying Parties): the server reads a Handle at initiation, accepts it if the
            # Verifier issued it, returns it and recomputes the binding with it.
            decls = "table vhandles(bitstring).\n"
            s_new = "in(c, n: bitstring);\n  get vhandles(=n) in\n  "
            a_in = "in(c, n: bitstring);" if rrp == "norrp" else "in(c, (n: bitstring, sid: bitstring));"
            s_out = "out(c, n);" if rrp == "norrp" else "out(c, (n, id));"
            a_rd = f"h((n, {a_sid}tgt, csr))"
            s_rd = f"h((n, {s_sid}tgt, csr))"
            v_def = "\nlet VerifierH() =\n  new n: bitstring;\n  insert vhandles(n);\n  out(c, n).\n"
            v_par = " | !VerifierH()"
            fresh = "the Handle"
            title = "Enrollment with Handles issued by a Verifier and accepted by both servers (one Handle originator shared across Relying Parties)"
        else:
            # Absent-timestamp: the Attester stamps Evidence with its own time value and sends it in
            # the request; the server recomputes the binding with the value it receives. Time windows
            # are not modelled: the timestamp is a fresh public value the Attester creates. The
            # server returns server_id; only rrp-from-initiate reads it.
            s_new = ""
            a_in = ("in(c, sid: bitstring);" if rrp == "rrp-from-initiate" else "in(c, _: bitstring);") + "\n  new ts: bitstring;\n  out(c, ts);"
            s_out = "out(c, id);"
            a_ts = "ts, "
            s_ts = "ts: bitstring, "
            a_rd = f"h((ts, {a_sid}tgt, csr))"
            s_rd = f"h((ts, {s_sid}tgt, csr))"
            fresh = "the timestamp"
            title = "Enrollment with a timestamp of the Attester's own, sent in the request, in place of a Handle (absent-timestamp; the timestamp is a fresh public value)"
        if rrp == "rrp-from-initiate":
            decls += "event AttesterBinds(bitstring, bitstring, bitstring).\n"
            a_binds = "\n  event AttesterBinds(sid, tgt, csr);"
        title += "; " + {"norrp": f"Evidence binds {fresh}, the Target and the CSR, no server identity",
                         "rrp-from-initiate": f"Evidence binds {fresh}, the server_id received in the initiation response, the Target and the CSR, without comparison",
                         "rrp-configured": f"Evidence binds {fresh}, the server identity from the Attester's configuration, the Target and the CSR, without comparison"}[rrp]
    elif variant.startswith("epoch-"):
        # Absent-epoch with a remote initiate: the server creates no Handle, returns the public epoch
        # ep and recomputes the binding with ep; the Attester binds ep, not the epoch field it receives.
        decls = "const ep: bitstring.\n"
        s_new = ""
        if variant == "epoch-norrp":
            a_in = "in(c, _: bitstring);"
            a_rd = "h((ep, tgt, csr))"
            s_out = "out(c, ep);"
            s_rd = "h((ep, tgt, csr))"
        else:
            a_in = "in(c, (_: bitstring, sid: bitstring));"
            s_out = "out(c, (ep, id));"
            s_rd = "h((ep, id, tgt, csr))"
            if variant == "epoch-rrp-from-initiate":
                decls += "event AttesterBinds(bitstring, bitstring, bitstring).\n"
                a_binds = "\n  event AttesterBinds(sid, tgt, csr);"
                a_rd = "h((ep, sid, tgt, csr))"
            else:
                a_rd = "h((ep, srv, tgt, csr))"
        title = {"epoch-norrp": "Enrollment with a shared public epoch in place of a fresh Handle (absent-epoch, remote initiate); Evidence binds the epoch, the Target and the CSR, no server identity",
                 "epoch-rrp-from-initiate": "Enrollment with a shared public epoch in place of a fresh Handle; Evidence binds the epoch, the server_id received in the initiation response, the Target and the CSR, without comparison",
                 "epoch-rrp-configured": "Enrollment with a shared public epoch in place of a fresh Handle; Evidence binds the epoch, the server identity from the Attester's configuration, the Target and the CSR, without comparison"}[variant]
    else:
        a_in = "in(c, (n: bitstring, sid: bitstring));\n  if sid = srv then"
        if variant in ("bind-nocompare", "nonce-rrp-configured-uniqueness"):
            # No Attester-side comparison of the wire server_id: the Attester binds the server
            # identity from its own CAI configuration (srv), and TACRA keeps the CAS transparent.
            a_in = "in(c, (n: bitstring, sid: bitstring));"
        a_rd = "h((n, srv, tgt, csr))"
        s_out = "out(c, (n, id));"
        s_rd = "h((n, id, tgt, csr))"
        title = {"bind": "Enrollment with the pull request's binding: Handle, server_id, Target and CSR",
                 "bind-nocompare": "Enrollment with the full binding and no Attester-side server_id comparison: the bound server identity comes from the CAI configuration, the CAS stays transparent",
                 "bind-compromised-s2": "Enrollment with the full binding; the second server and its CA key are the attacker's",
                 "bind-tee-key-leaked": "Enrollment with the full binding; the TEE attestation key has leaked (an assumption made explicit)",
                 "nonce-rrp-configured-uniqueness": "Enrollment as bind-nocompare (fresh Handle, server identity from the Attester's configuration, no comparison), asking only whether two servers can issue for one CSR and Target"}[variant]
    if variant == "bind-compromised-s2":
        queries = """
query t: bitstring, x: bitstring; event(Issued(id1, t, x)) ==> event(AttesterIntends(id1, t, x)).
"""
        proc = "out(c, pk(tk)); out(c, pk(ca1)); out(c, ca2);\n  ( !Attester(id1, tA) | !Server(id1, ca1) )"
    else:
        queries = "\n" + {"rrp-from-initiate": Q1 + Q2 + Q3 + B1 + B2 + U1,
                          "nonce-norrp-uniqueness": U1,
                          "nonce-rrp-configured-uniqueness": U1,
                          "epoch-norrp": Q1 + U1,
                          "epoch-rrp-from-initiate": Q1 + B1 + U1,
                          "epoch-rrp-configured": Q1 + U1,
                          **{v: Q1 + B1 + U1 if v.endswith("rrp-from-initiate") else Q1 + U1 for v in FRESHNESS_SOURCES}}.get(variant, Q1 + Q2 + Q3)
        leak = " out(c, tk);" if variant == "bind-tee-key-leaked" else ""
        proc = "out(c, pk(tk)); out(c, pk(ca1)); out(c, pk(ca2));" + leak + "\n  ( !Attester(id1, tA) | !Server(id1, ca1) | !Server(id2, ca2)" + v_par + " )"
    if variant in RRP_SOURCE + FRESHNESS_SOURCES:
        # Without preciseActions, ProVerif lets one Attester session read two different initiation
        # responses, and U1 comes back "cannot be proved" with no attack trace; see README.md.
        decls = "set preciseActions = true.\n" + decls
    return HEADER.format(title=title) + decls + queries + f"""
let Attester(srv: bitstring, tgt: bitstring) =
  new csk: skey;
  let csr = (pk2b(pk(csk)), sign(pk2b(pk(csk)), csk)) in
  out(c, tgt);
  {a_in}
  event AttesterIntends(srv, tgt, csr);{a_binds}
  let ev = sign((meas, {a_rd}), tk) in
  out(c, (tgt, {a_ts}csr, ev)).

let Server(id: bitstring, ca: skey) =
  in(c, tgt: bitstring);
  {s_new}{s_out}
  in(c, (tgt2: bitstring, {s_ts}csr: bitstring, ev: bitstring));
  if tgt2 = tgt then
  let (m: bitstring, rd: bitstring) = checksig(ev, pk(tk)) in
  if m = meas then
  let (pkcb: bitstring, pop: bitstring) = csr in
  let pk2b(pkc) = pkcb in
  if checksig(pop, pkc) = pkcb then
  if rd = {s_rd} then
  event Issued(id, tgt, csr);
  out(c, sign((id, tgt, pkcb), ca)).
{v_def}
process
  {proc}
"""

def retrieval(variant: str) -> str:
    # variant: base (-00) | auth | auth-compromised-vault2
    auth = variant.startswith("auth")
    dec = "adec_auth(b, cek, vpk)" if auth else "adec(b, cek)"
    enc = "aenc_auth(sec, pkc, vk)" if auth else "aenc(sec, pkc)"
    title = {"base": "Retrieval as in draft -00: bundle encrypted to CEKpub (base mode)",
             "auth": "Retrieval with origin authentication of the bundle (HPKE mode_auth)",
             "auth-compromised-vault2": "Retrieval with origin authentication; the second Vault's keys are the attacker's"}[variant]
    if variant == "auth-compromised-vault2":
        proc = "out(c, pk(tk)); out(c, pk(vk1)); out(c, vk2); out(c, sec2);\n  ( !AttesterR(id1, tA, pk(vk1)) | !Vault(id1, vk1, sec1) )"
    else:
        proc = "out(c, pk(tk)); out(c, pk(vk1)); out(c, pk(vk2));\n  ( !AttesterR(id1, tA, pk(vk1)) | !Vault(id1, vk1, sec1) | !Vault(id2, vk2, sec2) )"
    return HEADER.format(title=title) + """
query vid: bitstring, t: bitstring, s: bitstring; event(AttesterUses(vid, t, s)) ==> event(VaultReleased(vid, t, s)).
query attacker(sec1).
""" + f"""
let AttesterR(srv: bitstring, tgt: bitstring, vpk: pkey) =
  new cek: skey;
  out(c, tgt);
  in(c, (n: bitstring, sid: bitstring));
  if sid = srv then
  let ev = sign((meas, h((n, srv, tgt, pk2b(pk(cek))))), tk) in
  out(c, (tgt, pk2b(pk(cek)), ev));
  in(c, b: bitstring);
  let s = {dec} in
  event AttesterUses(srv, tgt, s).

let Vault(id: bitstring, vk: skey, sec: bitstring) =
  in(c, tgt: bitstring);
  new n: bitstring;
  out(c, (n, id));
  in(c, (tgt2: bitstring, pkcb: bitstring, ev: bitstring));
  if tgt2 = tgt then
  let pk2b(pkc) = pkcb in
  let (m: bitstring, rd: bitstring) = checksig(ev, pk(tk)) in
  if m = meas then
  if rd = h((n, id, tgt, pkcb)) then
  event VaultReleased(id, tgt, sec);
  out(c, {enc}).

process
  {proc}
"""

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    for f in os.listdir(here):
        if f.endswith(".pv"):
            os.remove(os.path.join(here, f))
    files = {
        "enrollment-nobind.pv": enrollment("nobind"),
        "enrollment-serveronly.pv": enrollment("serveronly"),
        "enrollment-bind.pv": enrollment("bind"),
        "enrollment-bind-nocompare.pv": enrollment("bind-nocompare"),
        "enrollment-bind-compromised-s2.pv": enrollment("bind-compromised-s2"),
        "enrollment-bind-tee-key-leaked.pv": enrollment("bind-tee-key-leaked"),
        "enrollment-rrp-from-initiate.pv": enrollment("rrp-from-initiate"),
        "enrollment-nonce-norrp-uniqueness.pv": enrollment("nonce-norrp-uniqueness"),
        "enrollment-nonce-rrp-configured-uniqueness.pv": enrollment("nonce-rrp-configured-uniqueness"),
        "enrollment-epoch-norrp.pv": enrollment("epoch-norrp"),
        "enrollment-epoch-rrp-from-initiate.pv": enrollment("epoch-rrp-from-initiate"),
        "enrollment-epoch-rrp-configured.pv": enrollment("epoch-rrp-configured"),
        "enrollment-epoch-received-norrp.pv": enrollment("epoch-received-norrp"),
        "enrollment-epoch-received-rrp-from-initiate.pv": enrollment("epoch-received-rrp-from-initiate"),
        "enrollment-epoch-received-rrp-configured.pv": enrollment("epoch-received-rrp-configured"),
        "enrollment-verifier-handles-norrp.pv": enrollment("verifier-handles-norrp"),
        "enrollment-verifier-handles-rrp-from-initiate.pv": enrollment("verifier-handles-rrp-from-initiate"),
        "enrollment-verifier-handles-rrp-configured.pv": enrollment("verifier-handles-rrp-configured"),
        "enrollment-timestamp-norrp.pv": enrollment("timestamp-norrp"),
        "enrollment-timestamp-rrp-from-initiate.pv": enrollment("timestamp-rrp-from-initiate"),
        "enrollment-timestamp-rrp-configured.pv": enrollment("timestamp-rrp-configured"),
        "retrieval-base.pv": retrieval("base"),
        "retrieval-auth.pv": retrieval("auth"),
        "retrieval-auth-compromised-vault2.pv": retrieval("auth-compromised-vault2"),
    }
    for name, text in files.items():
        with open(os.path.join(here, name), "w") as f:
            f.write(text)
        print("wrote", name)
