#!/usr/bin/env python3
"""Generate the four ProVerif models of the EST profile of TACRA from one template, so that the
"with" and "without" variants cannot drift apart.

  enrollment-nobind.pv   Enrollment as in draft-novak-lamps-tacra-est-00: Evidence binds the
                         Freshness Handle and the CSR, not the server. Expected: attack found
                         (server substitution by the conduit).
  enrollment-bind.pv     Enrollment with the Evidence-to-Target binding of the pull request
                         (server_id in the binding input, checked by the Attester and the CA).
                         Expected: the correspondence holds.
  retrieval-base.pv      Retrieval with the bundle "encrypted to CEKpub" (base mode, no origin
                         authentication). Expected: attack found (bundle substitution).
  retrieval-auth.pv      Retrieval with origin authentication (HPKE mode_auth: the recipient
                         needs the sender's public key to decrypt). Expected: holds.

The attacker is the network, i.e. the untrusted conduit (EST Client and EST Server as conduits) of
TACRA Section 7.2. The TEE attestation key, the CA keys, the Vault keys and the Vault secrets are
private. Two servers exist: S1, the one the Attester intends, and S2, another honest server the
attacker can talk to. Nothing is dishonest except the network.
"""
import os, sys

HEADER = """(* {title}
   Generated by gen.py; do not edit by hand. ProVerif 2.05 syntax. *)

free c: channel.

type skey.
type pkey.
fun pk(skey): pkey.
fun pk2b(pkey): bitstring [data].   (* a public key as a bitstring, for signing and tupling *)

(* signatures: the TEE attestation key, the CSR's proof of possession, the CA *)
fun sign(bitstring, skey): bitstring.
reduc forall m: bitstring, k: skey; checksig(sign(m, k), pk(k)) = m.

(* collision-resistant hash for the binding input *)
fun h(bitstring): bitstring.

(* public-key encryption "to CEKpub", base mode: anyone holding the public key can produce a
   well-formed ciphertext *)
fun aenc(bitstring, pkey): bitstring.
reduc forall m: bitstring, k: skey; adec(aenc(m, pk(k)), k) = m.

(* public-key encryption with sender authentication (HPKE mode_auth, RFC 9180 Section 5.1.3):
   decryption succeeds only under the sender's public key *)
fun aenc_auth(bitstring, pkey, skey): bitstring.
reduc forall m: bitstring, kr: skey, ks: skey; adec_auth(aenc_auth(m, pk(kr), ks), kr, pk(ks)) = m.

free tk: skey [private].          (* the TEE attestation key: genuine hardware *)
const meas: bitstring.            (* the workload's launch measurement *)
const id1: bitstring.             (* server_id of S1, the server the Attester intends *)
const id2: bitstring.             (* server_id of S2, another honest server *)
free ca1: skey [private].
free ca2: skey [private].
free vk1: skey [private].         (* origin keys of the Secret Vaults *)
free vk2: skey [private].
free secret1: bitstring [private].
free secret2: bitstring [private].

event AttesterIntends(bitstring, bitstring).   (* target server_id, CSR *)
event Issued(bitstring, bitstring).            (* issuing server_id, CSR *)
event VaultReleased(bitstring, bitstring).     (* vault server_id, secret *)
event AttesterUses(bitstring, bitstring).      (* intended server_id, secret the Attester will use *)
"""

ENROLL_QUERY = """
(* A certificate issued by a server for a CSR must have been intended for that server by the
   Attester that produced the CSR. *)
query sid: bitstring, x: bitstring; event(Issued(sid, x)) ==> event(AttesterIntends(sid, x)).
"""

RETRIEVE_QUERY = """
(* A secret the Attester decrypts and uses must have been released by the Vault it intended. *)
query vid: bitstring, s: bitstring; event(AttesterUses(vid, s)) ==> event(VaultReleased(vid, s)).
"""

def enrollment(bind: bool) -> str:
    if bind:
        att_in = "in(c, (n: bitstring, sid: bitstring));\n  if sid = target then"
        att_rd = "h((n, target, csr))"
        srv_out = "out(c, (n, id));"
        srv_rd = "h((n, id, csr))"
        title = "TACRA EST profile, enrollment WITH the Evidence-to-Target binding (server_id in the binding input)"
    else:
        att_in = "in(c, n: bitstring);"
        att_rd = "h((n, csr))"
        srv_out = "out(c, n);"
        srv_rd = "h((n, csr))"
        title = "TACRA EST profile, enrollment as in -00: Evidence binds the Handle and the CSR only"
    return HEADER.format(title=title) + ENROLL_QUERY + f"""
(* The Attester: generates CSK and CSR, obtains the AttestationInitiationResponse through the
   conduit, produces Evidence over the binding input, hands CSR and Evidence to the conduit. *)
let Attester(target: bitstring) =
  new csk: skey;
  let csr = (pk2b(pk(csk)), sign(pk2b(pk(csk)), csk)) in
  {att_in}
  event AttesterIntends(target, csr);
  let rd = {att_rd} in
  let ev = sign((meas, rd), tk) in
  out(c, (csr, ev)).

(* An EST Server with its Credential Authority: issues a Handle, receives CSR and Evidence
   through the conduit, verifies the Evidence under the TEE key, the measurement, the proof of
   possession and the binding, then issues. *)
let Server(id: bitstring, ca: skey) =
  new n: bitstring;
  {srv_out}
  in(c, (csr: bitstring, ev: bitstring));
  let (m: bitstring, rd: bitstring) = checksig(ev, pk(tk)) in
  if m = meas then
  let (pkcb: bitstring, pop: bitstring) = csr in
  let pk2b(pkc) = pkcb in
  if checksig(pop, pkc) = pkcb then
  if rd = {srv_rd} then
  event Issued(id, csr);
  out(c, sign((id, pkcb), ca)).

process
  out(c, pk(tk)); out(c, pk(ca1)); out(c, pk(ca2));
  ( !Attester(id1) | !Server(id1, ca1) | !Server(id2, ca2) )
"""

def retrieval(auth: bool) -> str:
    if auth:
        att_dec = "adec_auth(b, cek, vpk)"
        vault_enc = "aenc_auth(sec, pkc, vk)"
        title = "TACRA EST profile, retrieval WITH origin authentication of the bundle (HPKE mode_auth)"
    else:
        att_dec = "adec(b, cek)"
        vault_enc = "aenc(sec, pkc)"
        title = "TACRA EST profile, retrieval as in -00: bundle encrypted to CEKpub, base mode"
    return HEADER.format(title=title) + RETRIEVE_QUERY + f"""
(* The Attester in Retrieval mode: generates CEK, binds Handle, server_id and CEKpub into
   Evidence, receives the bundle through the conduit, decrypts, uses the secret. *)
let AttesterR(target: bitstring, vpk: pkey) =
  new cek: skey;
  in(c, (n: bitstring, sid: bitstring));
  if sid = target then
  let rd = h((n, target, pk2b(pk(cek)))) in
  let ev = sign((meas, rd), tk) in
  out(c, (pk2b(pk(cek)), ev));
  in(c, b: bitstring);
  let s = {att_dec} in
  event AttesterUses(target, s).

(* An EST Server with its Secret Vault: verifies Evidence and the binding, releases the secret
   encrypted to CEKpub. *)
let Vault(id: bitstring, vk: skey, sec: bitstring) =
  new n: bitstring;
  out(c, (n, id));
  in(c, (pkcb: bitstring, ev: bitstring));
  let pk2b(pkc) = pkcb in
  let (m: bitstring, rd: bitstring) = checksig(ev, pk(tk)) in
  if m = meas then
  if rd = h((n, id, pkcb)) then
  event VaultReleased(id, sec);
  out(c, {vault_enc}).

process
  out(c, pk(tk)); out(c, pk(vk1)); out(c, pk(vk2));
  ( !AttesterR(id1, pk(vk1)) | !Vault(id1, vk1, secret1) | !Vault(id2, vk2, secret2) )
"""

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    files = {
        "enrollment-nobind.pv": enrollment(False),
        "enrollment-bind.pv": enrollment(True),
        "retrieval-base.pv": retrieval(False),
        "retrieval-auth.pv": retrieval(True),
    }
    for name, text in files.items():
        with open(os.path.join(here, name), "w") as f:
            f.write(text)
        print("wrote", name)
